### ISSUE TITLE
isAbove is actually isEqualOrAbove

### ISSUE THREAD

**Issue by hahnzilla** [40Digits/sassqwatch#3]
Is there a reason that isAbove checks to see if it's greater than or equal to, but isBelow checks if it's just less than? 

It seems intentional because the comment above the function says:

```
Public: Checks if the current media query is greater than or equal to the specified breakpoint
```

**Comment by brandoncash** [comment]
This is to mimic how our media queries are set up; a 'large' query would also inherit from 'medium', for instance. `matches` should be a good alternative if it needs to be exact.
We could probably document that a bit better, or find a way to make it optional since it's tied to a mobile-first approach that assumes you are inheriting to larger sizes. For sure it's odd that the verbiage is identical to its counterpart, but the behavior is different.

**Comment by hahnzilla** [comment]
After a few days of you and Chad explaining it to me I get it. I'm not a huge fan of the verbiage, but it does make sense as to why it's that way now. Also, Chad showed me the wonders of using `max()` and `min()`
